version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: blockout
      POSTGRES_PASSWORD: blockout
      POSTGRES_DB: blockout
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - blockout-database:/var/lib/postgresql/data
    ports:
      - 5532:5432

  nextjs:
    container_name: nextjs
    build: ui
    ports:
      - 3000:3000
      - 5555:5555
    env_file:
      - ./ui/.env
    depends_on:
      - postgres
    volumes:
      - .:/application
    entrypoint: ["npx", "next", "dev"]

volumes:
  blockout-database:
