import Head from "next/head";
import { Canvas } from '@react-three/fiber'
import { Scene } from "./components/Scene";
import { GridHelper } from 'three';

export default function Home() {
  return (
    <>
      <Head>
        <title>Blockout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[rgb(253,244,173)] to-[#d7cffc]">
        <div className="scene">
          <Canvas shadows>
            <primitive object={new GridHelper(10, 10)} />
            <Scene width={5} height={9} depth={5} />
          </Canvas>
        </div>
      </main>
    </>
  );
}